### ISSUE TITLE
the office cifar is 5 train batch

### ISSUE THREAD

**Issue by here101** [haodonga/CIFAR-Dataset-master#1]
Dear researcher,
Thanks for your grate code,it's very helpful for me.
I have a question,the up-to-date cifar is 5 train batch,but your code is 4 train batch,if I don't change your code,will it cause bad influence?
Thanks your reply advance!

**Comment by haodonga** [comment]
Does not matter, 4 or 5 just the number of batchs, there is not influence for your performance, good luck!



发自我的iPhone


------------------ Original ------------------
From: here101 ***@***.***&gt;
Date: Wed,Dec 29,2021 2:41 PM
To: haodonga/CIFAR-Dataset-master ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [haodonga/CIFAR-Dataset-master] the office cifar is 5 train batch(Issue #1)

**Comment by here101** [comment]
哦，好的，谢谢大佬！
我懂了，只是分成了四个的话cifar.py里的代码还需要做一些微小的改动而已。
